---

- name: Python - Development Tools
  become: true
  package: 
    update_cache: yes
    state: "{{ python.state }}"
    name: "{{ item }}"
  loop:
    - python3-dev
    - python3-pip
    - python3-setuptools
    - virtualenv    
    - pipenv
  
