
- name: gui tools
  package:
    name: "{{ item }}"
    state: present
  loop:
    - dconf-cli
    - dconf-editor
    - gnome-shell-extension-prefs
    - gnome-tweaks
    - guake
    - timeshift
#    - redshift-gtk (night light available on recent distros)
  
- include_tasks: vscode.yml
  when: ansible_os_family == 'Debian'

- include_tasks: kvm.yml

- include_tasks: docker.yml

#- name: load dconf
#  shell: "dconf load /apps/guake/ < guake.dconf" 

# dconf write "/org/gnome/desktop/input-sources/xkb-options" "['caps:swapescape']"

