# See:
# https://docs.microsoft.com/en-us/azure/developer/ansible/install-on-linux-vm?tabs=azure-cli
# https://docs.microsoft.com/en-us/azure/developer/ansible/dynamic-inventory-configure?tabs=azure-cli

name: az-linux-devenv-ansible-playbook
on:
  workflow_run:
    workflows: ["AZ-TF-ENV Apply"]
    types: [completed]
  workflow_dispatch:

jobs:
  ansible-playbook-linux-dev:
    runs-on: self-hosted
    defaults:
      run:
        shell: bash
        working-directory: dev-env/linux/ansible-playbooks
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v2

      # - name: Update and Upgrade
      #   run: sudo apt update -y && sudo apt upgrade -y

      # - name: Setup Ansible
      #   run: sudo apt install -y wget git ansible python3-pip python-apt

      # - name: Install Azurerm plugin
      #   run: pip3 install ansible[azure]

      - name: Check Version
        run: ansible --version

      - name: Ping vm
        run: ping azenv-uks-dev-0.azbase.io -c 5

      # - name: Prereq (including ansible-apt)
      #   run: ansible-playbook -i inventory/cloud phase1.yml --tags prereq

      # Dynamic Inventory filename matters - should end with azure_rm.yml
      - name: prereq.yml (dynamic inventory)
        run: ansible-playbook -i inventory/linux_azure_rm.yml prereq.yml

      - name: phase1.yml (dynamic inventory)
        run: ansible-playbook -i inventory/linux_azure_rm.yml phase1.yml

      - name: Phase2.yml (dynamic inventory)
        run: ansible-playbook -i inventory/linux_azure_rm.yml phase2.yml
