name: az-tf-format
on:
  workflow_dispatch:

jobs:
  az-tf-fmt-and-raise-pr:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: azure-iac/terraform
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v2

      # Install the latest version of Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ secrets.TF_VERSION }}

      - name: Terraform version
        run: terraform version

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -recursive

      - name: set output for short sha
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Git commit and push
        id: push
        run: |
          git checkout -b temp/tf-fmt-${{ steps.vars.outputs.sha_short }}   
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Ran terraform fmt"
          git push origin temp/tf-fmt-${{ steps.vars.outputs.sha_short }}

      # publish results as a comment if workflow was a pull request
      # see: https://github.com/hashicorp/setup-terraform
      - uses: actions/github-script@0.9.0
        with:
          # use PAT to work around limitation on triggering actions from bot created PR
          github-token: ${{ secrets.TF_FMT_PR_TOKEN }}
          script: |
            const output = `#### Applied Terraform format
            #### Terraform fmt ⚙️ (below files have been modified)

            \`\`\`
            ${{ steps.fmt.outputs.stdout }}
            \`\`\`

            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Workflow: \`${{ github.workflow }}\`*`;
              
            github.pulls.create({
              title: "Terraform format workflow",
              owner: context.repo.owner,
              repo: context.repo.repo,
              head : "temp/tf-fmt-${{ steps.vars.outputs.sha_short }}",
              base : "main",
              body: output
            })
